### ISSUE TITLE
unpack requires a bytes object of length 1

### ISSUE THREAD

**Issue by 09williamsad** [Strackeror/MHW-LMT-Loader#1]
Blender version: 2.79b 2018-3-22
LMT-Loader version: Latest as of today
MHW-Importer version: Latest as of today

Issue:
Error occurs when importing a .lmt file to an imported .mod3 file.
Does not occur with the 2019-7-1 version.

Process:
Open blender
Import em101_00.mod3 using AsteriskAmpersand/Mod3-MHW-Importer with skeleton set to "Animation Armature"
Import em101_00.lmt using Strackeror/MHW-LMT-Loader
Error

Blender Error:
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\__init__.py", line 314, in execute
    animation = lmt.get_animation(id)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Lmt.py", line 37, in get_animation
    return readAt(BytesIO(self.full_data), self.animation_offsets[id], AnimationBlock)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Lmt.py", line 10, in readAt
    ret = class_def(data)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Lmt.py", line 69, in __init__
    self.bone_paths += [readAt(data, self.bone_paths_offset + len(BonePath()) * i, BonePath)]
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Lmt.py", line 10, in readAt
    ret = class_def(data)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Lmt.py", line 152, in __init__
    super().__init__(data, **kw)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Cstruct.py", line 175, in __init__
    self.marshall(data)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Cstruct.py", line 192, in marshall
    [self.__setattr__(attr, value) for attr, value in self.CStruct.marshall(data).items()]
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Cstruct.py", line 158, in marshall
    return {varName:typeOperator['deserializer'](data.read(typeOperator['size'])) for varName, typeOperator in self.struct.items()}
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Cstruct.py", line 158, in <dictcomp>
    return {varName:typeOperator['deserializer'](data.read(typeOperator['size'])) for varName, typeOperator in self.struct.items()}
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MHW-LMT-Loader-master\lmt\Cstruct.py", line 77, in <lambda>
    deserializer = lambda y: {'deserializer':lambda x: struct.unpack(y,x)[0], 'serializer': lambda x: struct.pack(y,x)}
struct.error: unpack requires a bytes object of length 1

location: <unknown location>:-1

Troubleshooting tried:
Reinstalling LMT Loader and MHW Importer
Restarting Blender
Restarting computer
Multiple .lmt files

MOD3 and LMT Files used uploaded here https://mega.nz/#!HC5B2AxQ!sJzSarJY0BBsAubY8wAXuMA4CxvL5NwEx2nLPEIxPak

**Comment by Strackeror** [comment]
The files work fine on my end, are you trying to load an animation ID that doesn't exist ?
Check the 'animation_' field on the bottom left when importing the LMT, put it back to '*' if you don't want a specific animation

**Comment by 09williamsad** [comment]
The animation ID starts as * and I have not changed it.
I have double checked today with the latest version, it still happens but the 2019-7-1 version does not have this issue with the same .lmt files.

**Comment by 09williamsad** [comment]
And I just tried it on another PC with a fresh install of blender and the plugins, same issue.
Tried a different monster aswell.
